### PR TITLE
Added spell items and effect tables from Core Rulebook

### PR DESCRIPTION
**Pull request by Stew-rt**
I've created spell items from the Core Rulebook, spells which have tables have them in descriptions and also have rolltables.
Due to Foundry not supporting nested folders, they are seperated as the following compendium packs:
"Spells $class $level"

### CODE REVIEW

**Comment by orffen** [comment]
Thank you! I will take a look at this when I have a moment, should merge and release this week.

**Comment by Stew-rt** [comment]
To be fair, I do wonder whether all this (and the armor/equipment currently in this system) should be a module called something like basicfantasyrpg-corebook.

**Comment by orffen** [comment]
> To be fair, I do wonder whether all this (and the armor/equipment currently in this system) should be a module called something like basicfantasyrpg-corebook.

I've had the same thought before, and that's maybe a better approach - but there are a lot of Foundry systems that just include compendiums directly as well. If it's in the system a user only needs to install the system - if it's in a module they need the module to get the nice compendiums.

I'd be quite happy for you to grab the weapons/armor/equipment and put it along with the spells into a separate module - I can update the readme to point people to the module instead. In future others could contribute compendiums with items and spells in other languages - I know the core book has been translated a number of times.

Let me know your thoughts.

**Comment by Stew-rt** [comment]
> > To be fair, I do wonder whether all this (and the armor/equipment currently in this system) should be a module called something like basicfantasyrpg-corebook.
> 
> I've had the same thought before, and that's maybe a better approach - but there are a lot of Foundry systems that just include compendiums directly as well. If it's in the system a user only needs to install the system - if it's in a module they need the module to get the nice compendiums.
> 
> I'd be quite happy for you to grab the weapons/armor/equipment and put it along with the spells into a separate module - I can update the readme to point people to the module instead. In future others could contribute compendiums with items and spells in other languages - I know the core book has been translated a number of times.
> 
> Let me know your thoughts.

I'll spend some time looking into how to go about publishing modules (hopefully it's trivial). As you say, I think it makes sense to have the core system clean, then you can add translations more trivially at a system level for sheet layouts and UI elements, and localised modules of items, actors etc can be imported from localised module packs.

**Comment by Stew-rt** [comment]
So i've made a repo at:
https://github.com/Stew-rt/basicfantasyrpg-corerules-en

I still need to correct the authors object.. it isn't working for some reason.. used a quite a handy github automation i stole from https://github.com/League-of-Foundry-Developers/FoundryVTT-Module-Template

**Comment by Stew-rt** [comment]
Looks like it works now.. if you like, you can close this PR and reference my repo.. or accept this pr and ignore my repo.

**Comment by orffen** [comment]
Fantastic, I'll clean up the system repo and add your repo to the README this weekend and close this out then.

Thanks!

**Comment by Stew-rt** [comment]
Closing this PR... so i can submit another one :imp: it isn't gunna be used, anyway.
I ballsed up this one and didn't branch my fork (d'oh)

**Pull request closed without merging**
