### PR TITLE
r9 - Vehicle actor sheets + a minor typo correction

### PR DESCRIPTION
**Pull request by miqued**
This request is to add an actor sheet for land vehicles and one for water vehicles, add localizations for their attributes, and changed "companium" to "companion" in the readme.

### CODE REVIEW

**Comment by miqued** [comment]
opensheets
selectionmenu

**Comment by orffen** [comment]
Thanks for submitting - I will review this one, but it may take me a while. It's a busy time of year 😄

**Comment by orffen** [comment]
At a glance, this one looks pretty good. I am about to release r9 to fix a bug #41 and need a little more time to review this one (and then clean up for the r10 release). 

Sorry for the delays on this one, it is on my list. I'm not sure I've ever used the vehicle rules, so I'll need to brush up on those as well :)

**Comment by orffen** [comment]
I've taken a look at this one but I've got a few thoughts about how I might want to implement this a little differently.

Are you using these sheets in your game already @miqued? Would love to hear how you're using them at the moment - are you doing much with them beyond tracking information?

- I'm not sure we need 2 separate sheets; I think the main thing to track is Movement, Hardness and HP (these are the only mechanical stats particularly relevant and are common cross both vehicle types)
- They should be defined as resources inside the system so that on the map we can get status bars for vehicle tokens
- I think a Siege Engine sheet would be a good idea as well, and then the natural extension of that is a Stronghold sheet; that allows for land battles

What do you think?

**Comment by orffen** [comment]
@miqued I've added my thoughts and notes in the individual issues below for each sheet. Would love to get your thoughts in there as well if you have time and inclination 🙂

- https://github.com/orffen/basicfantasyrpg/issues/50
- https://github.com/orffen/basicfantasyrpg/issues/48
- https://github.com/orffen/basicfantasyrpg/issues/49

**Comment by orffen** [comment]
Pretty pleased with this sheet - I'll close this pull request. Thanks so much for your work on this @miqued!

image

This will be included in r13. Also: 😁 
image

**Pull request closed without merging**
